os: osx
osx_image: xcode12

language: node_js
node_js:
  - node

before_install:
  - brew install yarn
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

script:
  - yarn
  - yarn dist
  - yarn release
