os: osx
osx_image: xcode12

language: node_js
node_js:
  - node

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn
  - yarn dist
  - yarn release
